language: php

php:
  - 5.4
  - 5.5

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache


before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - phpunit
