#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Jblt\Console\Command\XmlToMd;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new XmlToMd());
$application->run();