#!/usr/bin/env php
<?php
/**
 * (c) Demjan Kaluzki <kaluzkidemjan@gmail.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

require __DIR__.'/vendor/autoload.php';

$app = new Symfony\Component\Console\Application();
$app->addCommands([
    new kaluzki\JetBrains\LiveTemplate\Console\Command\XmlToMd()
]);
$app->run();